version: "3.6"
services:
  postgres:
    build:
      context: .
      dockerfile: pg-Dockerfile
    command: postgres -c 'max_connections=250' -c 'shared_buffers=256MB'
    ports:
      - "5432:5432"
    env_file:
      - .env
  graphql-engine:
    build:
      context: graphql-engine
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - "postgres"
volumes:
  backend-media:
